name: Expo CI CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      appName:
        description: "Application name"
        required: true
        default: "Sarah Store"
        type: string
      bundleIdentifier:
        description: "Application bundleIdentifier"
        required: true
        default: "com.yourcompany.yourappname"
        type: string
      slug:
        description: "Application slug"
        required: true
        default: "Sarah-App"
        type: string
      url:
        description: "Store URL"
        required: true
        default: "https://sarah-10.wuiltstore.com/"
        type: string
      icon:
        description: "Application icon"
        default: "https://raw.githubusercontent.com/SaraHassanAboEldahab/Mobile-App-builder/main/assets/icon.png"
        required: false
        type: string
      splash:
        description: "Application splash"
        default: " "
        required: false
        type: string
      adaptiveIcon:
        description: "Application adaptive-icon"
        default: " "
        required: false
        type: string
      email:
        description: "Application owner email"
        default: "s.aboeldahab@wuilt.com"
        required: true
        type: string
jobs:
  Build-for-android:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ github.event.inputs.appName }}
      SLUG: ${{ github.event.inputs.slug }}
      URL: ${{ github.event.inputs.url }}
      ICON: ${{ github.event.inputs.icon }}
      SPLASH: ${{ github.event.inputs.splash }}
      ADAPTIVE_ICON: ${{ github.event.inputs.adaptiveIcon }}
      BUNDLE_IDENTIFIER: ${{ github.event.inputs.bundleIdentifier }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "9.0.4" # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install deps
        run: yarn install
      - name: Build Android APK Bundle
        run: yarn build:android > build-android.log
      - name: Get build-android.log
        id: log
        # TODO extract download link
        run: echo ::set-output name=log::$(awk -F  'Successfully built standalone app:' '{print $2 "."}' build-android.log)
      - uses: dawidd6/action-send-mail@v3.6.1
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Building android app job result
          # Required recipients' addresses:
          to: ${{ github.event.inputs.email }}
          # Required sender full name (address can be skipped):
          from: WUilt
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build android completed successfully! ${{ steps.log.outputs.log }}
          # Optional HTML body read from file:
          html_body: Build android completed successfully! ${{ steps.log.outputs.log }}
          priority: low

  build-for-IOS:
    if: ${{ false }} # disable ios for now TODO: remove this
    runs-on: macos-latest
    env:
      APP_NAME: ${{ github.event.inputs.appName }}
      SLUG: ${{ github.event.inputs.slug }}
      URL: ${{ github.event.inputs.url }}
      ICON: ${{ github.event.inputs.icon }}
      SPLASH: ${{ github.event.inputs.splash }}
      ADAPTIVE_ICON: ${{ github.event.inputs.adaptiveIcon }}
      BUNDLE_IDENTIFIER: ${{ github.event.inputs.bundleIdentifier }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "9.0.4" # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          apple-id: ${{ secrets.EXPO_APPLE_ID }} # Apple ID to download from Apple Developer when Xcode not available in local
          apple-id-password: ${{ secrets.EXPO_APPLE_PASSWORD }}
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install deps
        run: yarn install
      - name: Build iOS app
        run: yarn build:ios  > build-ios.log
        env:
          EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
          EXPO_APPLE_PASSWORD: ${{ secrets.EXPO_APPLE_PASSWORD }}
          app_specific_password: ${{ secrets.EXPO_APP_SPECIFIC_PASSWORD  }}

      - name: Get build-ios.log
        id: log
        run: echo ::set-output name=log::$(cat build-ios.log)
      - uses: dawidd6/action-send-mail@v3.6.1
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Building iso app job result
          # Required recipients' addresses:
          to: ${{ github.event.inputs.email }}
          # Required sender full name (address can be skipped):
          from: WUilt
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build ios completed successfully! ${{ steps.log.outputs.log }}
          # Optional HTML body read from file:
          html_body: Build ios completed successfully! ${{ steps.log.outputs.log }}
          priority: low
